trigger:
- master

pool:
  #vmImage: 'windows-2019'
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  submodules: true  

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'pedromx94DH'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Build services'
    includeSourceTags: true
    includeLatestTag: true
    
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'pedromx94DH'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Push services'
    includeSourceTags: true
    includeLatestTag: true