trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- checkout: self
  submodules: true  

- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '4.3.0'
    checkLatest: true

- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'pedromx94DH'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Build services'
    includeSourceTags: true
    includeLatestTag: true
    
- task: DockerCompose@0
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryEndpoint: 'pedromx94DH'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Push services'
    includeSourceTags: true
    includeLatestTag: true